import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Strip out the duplicate CSS generated by the previous script
duplicate_style = """    <style>
        .content {
            transition: opacity 0.15s ease-in-out;
        }

        .hero {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 2rem;
            margin-bottom: 4rem;
            flex-wrap: wrap-reverse;
        }

        @media (min-width: 769px) {
            .hero {
                flex-wrap: nowrap;
            }
        }

        .action-btn {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.6rem 1.2rem;
            border: 1px solid #e5e5e5;
            border-radius: 8px;
            font-weight: 600;
            color: #000;
            background: #fff;
            transition: background 0.2s;
            text-decoration: none !important;
            background-image: none !important;
        }

        .action-btn:hover {
            background: #f8f9fa;
        }

        .post-item a {
            background-image: none !important;
        }

        .post-item a:hover {
            text-decoration: underline;
        }
    </style>"""

# It's safer to just regex replace `.hero { margin-bottom: 4rem; }` everywhere.
content = content.replace('margin-bottom: 4rem;\n            flex-wrap: wrap-reverse;', 'margin-bottom: 1rem;\n            flex-wrap: wrap-reverse;')


# 2. Fix the date font style removing uppercase and letter-spacing
old_date_style = 'style="display: block; color: #888; font-size: 0.85rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 0.5rem;"'
new_date_style = 'style="display: block; color: #666; font-size: 0.95rem; font-weight: 500; margin-bottom: 0.5rem;"'
content = content.replace(old_date_style, new_date_style)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)
